In [3]:
# importing numpy -> pip install numpy
import numpy as np 
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(np.__version__) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
2.0.0


CREATION OF ARRAYS
we can create array by using array() function

In [4]:
arr=np.array((1,2,3))
print(arr)

[1 2 3]


DIMENSIONALITY IN ARRAYS

In [19]:
# 0D array
a=np.array(34)
print(arr)
print(a.ndim)
# 1 D array
b=np.array([13,56,45,34]) 
print("----------------------------------------------------------\n",b)
print(b.ndim)
# 2D array -- that has 1 D arrays as the elements
c=np.array([[1,2,3],[5,6,7]])
print("----------------------------------------------------------\n",c)
print(c.ndim)
#3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

d=np.array([
    [[1,2,3],[5,6,7]],
    [[2,3,4],[7,8,9]]
              ])
print("----------------------------------------------------------\n",d)
print(d.ndim)

# 4 dim where each elem is 3 dim (has 3 D array as element)
e=np.array([
    [[[1,2,3],[4,5,6],[6,7,8]],
    [[2,3,4],[5,6,7],[7,8,9]]]
    ])
print("----------------------------------------------------------\n",e)
print(e.ndim)

[[[1 2 3]
  [5 6 7]]

 [[2 3 4]
  [7 8 9]]]
0
----------------------------------------------------------
 [13 56 45 34]
1
----------------------------------------------------------
 [[1 2 3]
 [5 6 7]]
2
----------------------------------------------------------
 [[[1 2 3]
  [5 6 7]]

 [[2 3 4]
  [7 8 9]]]
3
----------------------------------------------------------
 [[[[1 2 3]
   [4 5 6]
   [6 7 8]]

  [[2 3 4]
   [5 6 7]
   [7 8 9]]]]
4


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.



In [22]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


INDEXING

positive step -  starts from given index and goes forward till last-1
negative step - starts from given index and goes backward till last-1

In [43]:
# one dim array
arr=np.array([45,56,67,78,89,90])
print(arr[0])
print(arr[-1])
# print(arr[-8]) , print(arr[9])-- out of bounds
print(arr[-3:]) # from -3 index to last
print(arr[-3::-1]) # from -3 to 0 index as we are using -1 here so it goes backward with step 1
print(arr[:]) # goes from start to end with step 1
print(arr[::-1]) 
print(arr[-4:-1:-1]) # empty as it will start from -4 in backward , it will not find -1 there
print(arr[-1:-4])


45
90
[78 89 90]
[78 67 56 45]
[45 56 67 78 89 90]
[90 89 78 67 56 45]
[]
[]


In [40]:
# 2 DIM ARRAY -- using , to represent dim and element
arr=np.array([[1,2,3,4,5,6],[4,5,6,7,9,0]])
print(arr[1])
print(arr[0,3])
print(arr[1,5])

[4 5 6 7 9 0]
4
0


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

In [41]:
# 3 dim array
arr=np.array([
    [[2,3,4]],[[3,4,5]]
    ])
print(arr[0,0,2]) #4
print(arr[1,0,1]) #4


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

4
4


In [42]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


ARRAY SLICING (colon is used)
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [48]:
#slicing 2D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

# from both elements get 2nd index
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


DATATYPES IN NUMPY
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.

NUMPY
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [51]:
arr = np.array(["apple", 'banana', 'cherry'])

print(arr.dtype)

arr = np.array([12,3,4])
print(arr.dtype)

<U6
int64


In [65]:
# we can define datatype explicitlly AT THE TIME OF CREATION
# For i, u, f, S and U we can define size as well
# ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i8') # 8 bytes ie 64 bits int

print(arr)
print(arr.dtype)

arr=np.array([1,2,5.6,"mehak"])
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int64
['1' '2' '5.6' 'mehak']
<U32


In [72]:
# changing the dataype for existing array using astype()
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


arr = np.array([1, 0, 3]) # 0 is false rest are true

newarr = arr.astype(bool) # we can use keyword also like int,bool,float,str

print(newarr)
print(newarr.dtype)

[1 2 3]
int32
['1' '0' '3']
<U21


COPY AND VIEW
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [77]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
print("---------------------------------------")
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
print("---------------------------------------")
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
---------------------------------------
[42  2  3  4  5]
[42  2  3  4  5]
---------------------------------------
[31  2  3  4  5]
[31  2  3  4  5]


Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [78]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [82]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  # (2,4) -- The example above returns (2, 4), which means that the array has 2 dimensions,
# where the first dimension has 2 elements and the second has 4.

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)
print(arr[0,0,0,0,2])

# Integers at every index tells about the number of elements the corresponding dimension has.
# In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
3


Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [83]:
#The outermost dimension will have 4 arrays, each with 3 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [85]:
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [84]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)  # hence it does not owns the array

[1 2 3 4 5 6 7 8]


You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.
We can not pass -1 to more than one dimension.

In [86]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
