It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy, dimensions are called axes. The number of axes is rank.
NumPy’s array class is called ndarray. It is also known by the alias array.

In [ ]:
import numpy as np

In [ ]:


# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


CREATION


In [ ]:
import numpy as np

# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


In [ ]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("An array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("An array initialized with all 6s." 
            "Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("A random array:\n", e)


In [ ]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("A sequential array with steps of 5:\n", f)


In [ ]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("A sequential array with 10 values between"
                                 "0 and 5:\n", g)


In [ ]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)


In [ ]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()

print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)


Slicing: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
Integer array indexing: In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding elements is done to construct a new arbitrary array.
Boolean array indexing: This method is used when we want to pick elements from the array which satisfy some condition.

In [ ]:
# Python program to demonstrate
# indexing in numpy
import numpy as np

# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


SORTING

In [ ]:
# Python program to demonstrate sorting in numpy
import numpy as np

a = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a, axis = None))

# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(a, axis = 1))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(a, axis = 0, kind = 'mergesort'))

#-----------------------------------------------------------------------------------IMPORTANT
# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


In [ ]:

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')  # f for column major

In [ ]:
np.zeros([4, 3], 
         dtype = np.int32,
         order = 'C')  # C for row major

In [ ]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

dtype

In NumPy, the np.dtype function is used to define a custom data type (dtype) for structured arrays. This allows you to create arrays with fields of different data types, similar to how a record in a database or a row in a spreadsheet might contain different types of data. 

[('name', np.str_, 16), ('grades', np.float64, (2,))]: This is a list of tuples, where each tuple defines a field in the structured array.

('name', np.str_, 16): This defines a field named 'name' which will store strings (np.str_) with a maximum length of 16 characters.

('grades', np.float64, (2,)): This defines a field named 'grades' which will store an array of two 64-bit floating-point numbers (np.float64).
(2,): This is a shape tuple that indicates the 'grades' field will store a one-dimensional array with 2 elements.

In [9]:
# Python program to demonstrate
# the use of data type object with structured array.
import numpy as np

dt = np.dtype([('name', np.str_, 16), ('grades', np.float64, (2,))])

# x is a structured array with names and marks of students.
# Data type of name of the student is np.str_ and
# data type of marks is np.float(64)
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)

print(x[1])
print("Grades of John are: ",x[1]['grades'])
print("Names are: ",x['name'])


('John', [6.+0.j, 7.+0.j])
Grades of John are:  [6.+0.j 7.+0.j]
Names are:  ['Sarah' 'John']


R : Number of rows
C : [optional] Number of columns; By default M = N
k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
dtype : [optional, float(by Default)] Data type of returned array.  

In [13]:
 
# 2x2 matrix with 1's on main diagonal
b = np.eye(2, dtype = float)
print("Matrix b : \n", b)
 
# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
a = np.eye(4, 5, k =-1)
print("\nMatrix a : \n", a)

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


APPENDING IN NUMPY ARRAY

In [ ]:
# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)
 
# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)

In [ ]:

arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

combined = np.append(arr, arr_float)
print(combined) # Output: [1. 2. 3. 4. 5.]


In [ ]:

# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
 
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

STACKING

In [ ]:
# Python program explaining 
# hstack() function 

import numpy as geek 

# input array 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


In [ ]:
# Python program explaining 
# vstack() function 

import numpy as geek 

# input array 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays vertically 
out_arr = geek.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 


To compare arrays

In [ ]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)


In [ ]:
import numpy as np


a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a: ", a)
print("Array b: ", b)

print("a > b")
print(np.greater(a, b))

print("a >= b")
print(np.greater_equal(a, b))

print("a < b")
print(np.less(a, b))

print("a <= b")
print(np.less_equal(a, b))


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


# Comparing the arrays
if np.array_equal(arr1, arr2):
	print("Equal")
else:
	print("Not Equal")


Union of arrays: result is 1D

In [ ]:
# import libraries 
import numpy as np 


# 2-d array 
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
print("array1 ") 
print(arr1) 

arr2 = np.array([0, 5, 10]) 
print("array2 ", arr2) 

# print union of 2-d array and 1-d array 
print("Union of two arrays", np.union1d(arr1, arr2)) 


Syntax : np.unique(Array)
Return : Return the unique of an array.

In [ ]:
# import numpy 
import numpy as np 

a = [1, 2, 2, 4, 3, 6, 4, 8] 

# using np.unique() method 
gfg = np.unique(a) 

print(gfg) 


In [ ]:
import numpy as geek 

gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 

# without trim parameter 
# returns an array without leading and trailing zeros 

res = geek.trim_zeros(gfg) 
print(res) 
res = geek.trim_zeros(gfg, 'f')  # f or b for forward or backward
print(res)

RANDOM SAMPLING

In [17]:
# Python program explaining 
# numpy.random.ranf() function 

# importing numpy 
import numpy as geek 


# output random float value 
out_val = geek.random.rand(4)  # or ranf we can give size or by default it is none and returns one value only
print ("Output random float value : ", out_val) 


Output random float value :  [0.45803914 0.51092803 0.31187432 0.49428021]


In [20]:
val=np.random.random(3) # float value we can pass size and shape here too
print(val)
# output random value 
out_val = np.random.random_sample() 
print ("Output random float value : ", out_val)  

[0.81922387 0.11659492 0.48199403]
Output random float value :  0.8689136222688045


In [22]:
# output array 
out_arr = geek.random.randint(2, 10, (2, 3, 4))  # low, high, shape
print ("Output 3D Array filled with random integers : ", out_arr)  

v=np.random.randint(9) # takes one necessary output which is high
print(v)

Output 3D Array filled with random integers :  [[[2 6 3 9]
  [4 9 4 4]
  [6 2 5 7]]

 [[3 5 6 8]
  [7 9 8 8]
  [2 4 2 7]]]
8


Syntax : numpy.random.choice(a, size=None, replace=True, p=None)

1) a – 1-D array of numpy having random samples.

2) size – Output shape of random samples of numpy array.

3) replace – Whether the sample is with or without replacement.

4) p – The probability attach with every samples in a. 

Output : Return the numpy array of random samples.

In [23]:
val=np.random.choice([12,45,67,89],2)
print(val)

[45 12]


SEARCHING IN ARRAY
Syntax: numpy.where(condition[, x, y]) 

Parameters:

condition : When True, yield x, otherwise yield y.
x, y : Values from which to choose. x, y and condition need to be broadcastable to some shape.

In [24]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45]) 
  
#  printing arr 
print("arr = {}".format(arr)) 
  
#  looking for value 30 in arr and storing its index in i 
i = np.where(arr == 30) # return index
print("i = {}".format(i))

arr = [10 32 30 50 20 82 91 45]
i = (array([2]),)


In [25]:
# Python code demonstrate statistical function 
import numpy as np 

# construct a weight array 
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45]) 

# minimum and maximum 
print('Minimum and maximum weight of the students: ') 
print(np.amin(weight), np.amax(weight)) 

# range of weight i.e. max weight-min weight 
print('Range of the weight of the students: ') 
print(np.ptp(weight)) 

# percentile 
print('Weight below which 70 % student fall: ') 
print(np.percentile(weight, 70)) 

# mean 
print('Mean weight of the students: ') 
print(np.mean(weight)) 

# median 
print('Median weight of the students: ') 
print(np.median(weight)) 

# standard deviation 
print('Standard deviation of weight of the students: ') 
print(np.std(weight)) 

# variance 
print('Variance of weight of the students: ') 
print(np.var(weight)) 

# average 
print('Average weight of the students: ') 
print(np.average(weight)) 


Minimum and maximum weight of the students: 
45.0 73.25
Range of the weight of the students: 
28.25
Weight below which 70 % student fall: 
55.317
Mean weight of the students: 
54.3225
Median weight of the students: 
51.6
Standard deviation of weight of the students: 
8.052773978574091
Variance of weight of the students: 
64.84716875
Average weight of the students: 
54.3225
