# np array and basic operations

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

In [1]:

import numpy as np

In [40]:
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
				[ 4, 2, 5]] ) 

# Printing type of arr object 
print("Array is of type: ", type(arr)) 

# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

# Printing shape of array 
print("Shape of array: ", arr.shape) 

# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 

# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [67]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) #rank 2
print(arr)
print(arr[:2,::2])
arr=np.array(((1,2,0,4),(2,-4,5,7)))# creating an array using tuple
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [4 6]]
[[ 1  2  0  4]
 [ 2 -4  5  7]]


In [68]:
print(arr[1][2])
# boolean array indexing example 
cond = arr > 0 # cond is a boolean array 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 

5

Elements greater than 0:
 [1 2 4 2 5 7]


In [11]:
index=arr[[0,1,1],[2,3,0]]#slicing the particular elements from the array at once
print(index)

[3 7 2]


In [10]:
Index_arr = arr[[1, 1, 0, 1], 
                [1, 2, 1, 0]]
print ("\nElements at indices (1, 1), "
    "(1, 2), (0, 1), (1, 0):\n", Index_arr)


Elements at indices (1, 1), (1, 2), (0, 1), (1, 0):
 [4 5 2 2]


Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.

In [41]:
# Creating a 3X4 array with all zeros 
c = np.zeros((3, 4)) 
print ("An array initialized with all zeros:\n", c) 

# Create a constant value array of complex type 
d = np.full((3, 3), 6, dtype = 'complex') 
print ("An array initialized with all 6s."
			"Array type is complex:\n", d) 

# Create an array with random values 
e = np.random.random((2, 2)) 
print ("A random array:\n", e)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.30660584 0.24843913]
 [0.01554385 0.5117993 ]]


In [23]:
a1=np.array([[1,2],[4,5]])
a2=np.array([[1,5],[8,9]])
print(a1)
print(a2)
print("adding 1 to every element of a1\n",a1+1)
print("Subtractin 2 from every element of a2\n",a2-2)
print("unary operation on a1,sum of all the elements of a1:",a1.sum())
print("adding a1 and a2\n", a1*a2)# this is not giving matrix multiplication
#this way ae can add , sub divide the two arrays

[[1 2]
 [4 5]]
[[1 5]
 [8 9]]
adding 1 to every element of a1
 [[2 3]
 [5 6]]
Subtractin 2 from every element of a2
 [[-1  3]
 [ 6  7]]
unary operation on a1,sum of all the elements of a1: 12
adding a1 and a2
 [[ 1 10]
 [32 45]]


arange: This function returns evenly spaced values within a given interval. Step size is specified.

In [42]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("A sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


 linspace: It returns evenly spaced values within a given interval.

In [44]:
# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("A sequential array with 10 values between \"0 and 5\":\n", g)


A sequential array with 10 values between "0 and 5":
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Reshaping an array in Python means changing the shape of an array without changing its contents. It is a common operation performed when working with arrays in Python. By reshaping, we can add or remove dimensions or change the number of elements in each dimension 

In [64]:
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
				[5, 2, 4, 2], 
				[1, 2, 0, 1]]) 

newarr = arr.reshape(2, 2, 3) # it gives 2 arrays of shape 2*3(number of arrays,rows,columns)
arr1=arr.reshape(4,3)  # reshaping the array into 4 rows and 3 columns
print(arr1)
print("---------------")
print ("Original array:\n", arr) 
print("---------------") 
print ("Reshaped array:\n", newarr)


[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]
---------------
Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


'C': Flattens array elements into row-major order (C-style).
'F': Flattens array elements into column-major order (Fortran-style).
'A': Flattens array elements in column-major order if the array is Fortran contiguous in memory or row-major otherwise.
'K': Flattens array elements in the order the elements occur in memory.

In [61]:
flatten=arr.flatten(order="f")
print(arr)
print(flatten)

[[1 2 3 4]
 [2 4 5 7]]
[1 2 2 4 3 5 4 7]


# dtypes in numpy array

Every ndarray has an associated data type (dtype) object. This data type object (dtype) provides information about the layout of the array. The values of an ndarray are stored in a buffer which can be thought of as a contiguous block of memory bytes which can be interpreted by the dtype object. Numpy provides a large set of numeric datatypes that can be used to construct arrays. At the time of Array creation, Numpy tries to guess a datatype, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [24]:
# Integer datatype
# guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         
 
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype) 

Integer Datatype: 
int32

Float Datatype: 
float64


In [25]:
# forced datatype
a=np.array([1,2],dtype=np.int64)
print(a)
print(a.dtype)

[1 2]
int64


# math operations on numpy array

In [39]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
print(arr1)
print("-"*40)
print(arr2)
print("-"*40)
print("Addition of two arrays\n",np.add(arr1,arr2))
print("-"*40)
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("Addition of Array elements: ")
print(Sum1)
print("-"*40)
print("sraureroot of array 1:\n",np.sqrt(arr1))
print("-"*40)
print("Transpose of array 2:\n",arr2.T)

[[4. 7.]
 [2. 6.]]
----------------------------------------
[[3. 6.]
 [2. 8.]]
----------------------------------------
Addition of two arrays
 [[ 7. 13.]
 [ 4. 14.]]
----------------------------------------
Addition of Array elements: 
19.0
----------------------------------------
sraureroot of array 1:
 [[2.         2.64575131]
 [1.41421356 2.44948974]]
----------------------------------------
Transpose of array 2:
 [[3. 2.]
 [6. 8.]]


In [69]:
# Python program to demonstrate 
# unary operators in numpy 
import numpy as np 

arr = np.array([[1, 5, 6], 
				[4, 7, 2], 
				[3, 1, 9]]) 

# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", 
					arr.max(axis = 1)) 

# minimum element of array 
print ("Column-wise minimum elements:", 
						arr.min(axis = 0)) 

# sum of array elements 
print ("Sum of all array elements:", 
							arr.sum()) 

# cumulative sum along each row 
print ("Cumulative sum along each row:\n", 
						arr.cumsum(axis = 1)) 


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [70]:
# Python program to demonstrate 
# binary operators in Numpy 
import numpy as np 

a = np.array([[1, 2], 
			[3, 4]]) 
b = np.array([[4, 3], 
			[2, 1]]) 

# add arrays 
print ("Array sum:\n", a + b) 

# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 

# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc. 

In [71]:
# Python program to demonstrate 
# universal functions in numpy 
import numpy as np 

# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 

# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 

# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [73]:
# Python program to demonstrate sorting in numpy 
import numpy as np 

a = np.array([[1, 4, 2], 
				[3, 4, 6], 
			[0, -1, 5]]) 

# sorted array 
print ("Array elements in sorted order:\n", 
					np.sort(a, axis = None)) 

# sort array row-wise 
print ("Row-wise sorted array:\n", 
				np.sort(a, axis = 1)) 

# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
			np.sort(a, axis = 0, kind = 'mergesort')) 



Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


# structured array

In [ ]:
# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 

# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
		('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
			
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
			np.sort(arr, order = 'name')) 
			
print ("Array sorted by graduation year and then cgpa:\n", 
				np.sort(arr, order = ['grad_year', 'cgpa'])) 
